'use client'

import { useMemo, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { ArrowRight, BookOpen, Check, ChevronLeft, ChevronRight, CircleHelp, FileText, Flag, Gauge, LayoutDashboard, LockKeyhole, LogOut, Menu, Search, Shield, ShieldAlert, Sparkles, UserRound, X } from 'lucide-react'

type View = 'landing' | 'auth' | 'dashboard' | 'assessment' | 'results' | 'history' | 'knowledge' | 'profile'
type Question = { category: string; prompt: string; options: { label: string; points: number }[] }

const questions: Question[] = [
  { category: 'Passwords', prompt: 'How unique are your passwords across accounts?', options: [{ label: 'I reuse the same password everywhere', points: 4 }, { label: 'I reuse a few variations', points: 3 }, { label: 'Most accounts have unique passwords', points: 1 }, { label: 'I use a password manager', points: 0 }] },
  { category: 'Phishing', prompt: 'How do you handle unexpected links in emails or messages?', options: [{ label: 'I click if it looks familiar', points: 4 }, { label: 'I check the sender quickly', points: 3 }, { label: 'I verify the link and sender', points: 1 }, { label: 'I report it without opening', points: 0 }] },
  { category: 'Devices', prompt: 'How often do you install software and security updates?', options: [{ label: 'Only when something breaks', points: 4 }, { label: 'When I remember', points: 3 }, { label: 'Within a few weeks', points: 1 }, { label: 'Automatic updates are enabled', points: 0 }] },
  { category: 'Wi-Fi', prompt: 'How do you secure the networks you use most?', options: [{ label: 'I use public Wi-Fi for sensitive tasks', points: 4 }, { label: 'I use whatever network is available', points: 3 }, { label: 'I avoid sensitive tasks on public Wi-Fi', points: 1 }, { label: 'I use trusted networks and a VPN', points: 0 }] },
  { category: 'Backups', prompt: 'How prepared are you if files are lost or encrypted?', options: [{ label: 'I have no backups', points: 4 }, { label: 'I manually copy important files sometimes', points: 3 }, { label: 'I back up most devices', points: 1 }, { label: 'I have tested, offline backups', points: 0 }] },
  { category: 'Privacy', prompt: 'How much personal information do you share publicly?', options: [{ label: 'A lot, including routines and location', points: 4 }, { label: 'More than I probably should', points: 3 }, { label: 'I review privacy settings occasionally', points: 1 }, { label: 'I keep my digital footprint minimal', points: 0 }] },
  { category: 'Identity', prompt: 'Which protections are enabled on important accounts?', options: [{ label: 'Just a password', points: 4 }, { label: 'Security questions or SMS codes', points: 3 }, { label: 'Two-factor authentication on key accounts', points: 1 }, { label: 'Passkeys or authenticator app everywhere', points: 0 }] },
  { category: 'Awareness', prompt: 'How confident are you spotting a cyber threat?', options: [{ label: 'I usually cannot tell', points: 4 }, { label: 'I can spot obvious scams', points: 3 }, { label: 'I know common warning signs', points: 1 }, { label: 'I regularly keep up with security guidance', points: 0 }] },
]

const topics = [
  { title: 'Phishing', icon: Flag, tone: 'cyan', desc: 'Deceptive messages designed to steal credentials or money.', signs: ['Urgent requests', 'Lookalike domains', 'Unexpected attachments'], tips: ['Pause before clicking', 'Verify through a second channel', 'Use a password manager'] },
  { title: 'Ransomware', icon: LockKeyhole, tone: 'red', desc: 'Malware that encrypts files and demands payment.', signs: ['Locked files', 'Unusual extensions', 'Ransom notes'], tips: ['Keep offline backups', 'Patch devices promptly', 'Never pay without advice'] },
  { title: 'Identity Theft', icon: UserRound, tone: 'violet', desc: 'Unauthorized use of your personal information.', signs: ['Unknown transactions', 'New account alerts', 'Missing mail'], tips: ['Freeze credit quickly', 'Use unique passwords', 'Review account alerts'] },
  { title: 'Data Breaches', icon: FileText, tone: 'amber', desc: 'Exposed information from compromised organizations.', signs: ['Breach notices', 'Password reset emails', 'Suspicious logins'], tips: ['Change reused passwords', 'Enable MFA', 'Monitor accounts'] },
  { title: 'Malware', icon: ShieldAlert, tone: 'green', desc: 'Software built to damage, spy, or gain unauthorized access.', signs: ['Slow performance', 'Pop-ups', 'Unknown apps'], tips: ['Install from trusted stores', 'Keep antivirus active', 'Update your OS'] },
]

function scoreFor(answers: number[]) { const raw = answers.reduce((sum, value) => sum + value, 0); return Math.round(100 - (raw / 32) * 100) }
function riskFor(score: number) { return score >= 75 ? 'Low' : score >= 50 ? 'Medium' : 'High' }

export default function Page() {
  const [view, setView] = useState<View>('landing')
  const [mobileOpen, setMobileOpen] = useState(false)
  const [authMode, setAuthMode] = useState<'login' | 'signup'>('login')
  const [answers, setAnswers] = useState<number[]>([])
  const [step, setStep] = useState(0)
  const [selected, setSelected] = useState<number | null>(null)
  const [userEmail, setUserEmail] = useState('')
  const [password, setPassword] = useState('')
  const [authMessage, setAuthMessage] = useState('')
  const [search, setSearch] = useState('')
  const [topic, setTopic] = useState(topics[0])

  const score = useMemo(() => scoreFor(answers), [answers])
  const risk = riskFor(score)
  const filteredTopics = topics.filter((item) => item.title.toLowerCase().includes(search.toLowerCase()) || item.desc.toLowerCase().includes(search.toLowerCase()))

  const navigate = (next: View) => { setView(next); setMobileOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const startAssessment = () => { setAnswers([]); setStep(0); setSelected(null); navigate('assessment') }
  const chooseAnswer = (points: number) => { setSelected(points) }
  const nextQuestion = () => { if (selected === null) return; const next = [...answers, selected]; if (step === questions.length - 1) { setAnswers(next); navigate('results') } else { setAnswers(next); setStep(step + 1); setSelected(null) } }
  const submitAuth = async (event: React.FormEvent) => { event.preventDefault(); setAuthMessage(''); try { const supabase = createClient(); const result = authMode === 'login' ? await supabase.auth.signInWithPassword({ email: userEmail, password }) : await supabase.auth.signUp({ email: userEmail, password, options: { emailRedirectTo: process.env.NEXT_PUBLIC_DEV_SUPABASE_REDIRECT_URL ?? `${window.location.origin}/auth/callback` } }); if (result.error) throw result.error; if (authMode === 'signup' && !result.data.session) { setAuthMessage('Check your email to confirm your account.'); return } setAuthMessage('Signed in securely.'); navigate('dashboard') } catch (error) { setAuthMessage(error instanceof Error ? error.message : 'Unable to sign in. Please try again.') } }

  const nav = <>
    <button className="nav-item active" onClick={() => navigate('dashboard')}><LayoutDashboard size={17} /> Dashboard</button>
    <button className="nav-item" onClick={startAssessment}><Gauge size={17} /> Assessment</button>
    <button className="nav-item" onClick={() => navigate('history')}><FileText size={17} /> History</button>
    <button className="nav-item" onClick={() => navigate('knowledge')}><BookOpen size={17} /> Knowledge Base</button>
  </>

  if (view === 'landing') return <Landing onStart={() => navigate('auth')} onExplore={() => navigate('knowledge')} />
  if (view === 'auth') return <Auth mode={authMode} setMode={setAuthMode} email={userEmail} setEmail={setUserEmail} password={password} setPassword={setPassword} message={authMessage} onSubmit={submitAuth} onBack={() => navigate('landing')} />

  return <div className="app-shell">
    <aside className={`sidebar ${mobileOpen ? 'open' : ''}`}>
      <div className="brand"><span className="brand-mark"><Shield size={19} /></span><span>Cyber<span>Shield</span></span></div>
      <div className="side-label">Workspace</div>{nav}
      <div className="side-label">Account</div>
      <button className="nav-item" onClick={() => navigate('profile')}><UserRound size={17} /> Profile & Settings</button>
      <div className="sidebar-bottom"><div className="secure-mini"><LockKeyhole size={15} /><span>Data encrypted</span><Check size={13} /></div><button className="nav-item muted" onClick={() => navigate('landing')}><LogOut size={17} /> Sign out</button></div>
    </aside>
    <main className="content">
      <header className="topbar"><button className="icon-button mobile-only" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Open navigation">{mobileOpen ? <X size={19} /> : <Menu size={19} />}</button><div className="breadcrumbs">Workspace <span>/</span> <strong>{view === 'dashboard' ? 'Dashboard' : view[0].toUpperCase() + view.slice(1)}</strong></div><div className="top-actions"><button className="icon-button" aria-label="Help"><CircleHelp size={18} /></button><button className="avatar" onClick={() => navigate('profile')}>AS</button></div></header>
      <div className="page-wrap">
        {view === 'dashboard' && <Dashboard risk={risk} score={score} onStart={startAssessment} onKnowledge={() => navigate('knowledge')} onHistory={() => navigate('history')} />}
        {view === 'assessment' && <Assessment step={step} selected={selected} answerCount={answers.length} onSelect={chooseAnswer} onNext={nextQuestion} onBack={() => step ? (setStep(step - 1), setSelected(answers[step - 1] ?? null)) : navigate('dashboard')} />}
        {view === 'results' && <Results score={score} risk={risk} answers={answers} onRetake={startAssessment} onDashboard={() => navigate('dashboard')} />}
        {view === 'history' && <History onStart={startAssessment} />}
        {view === 'knowledge' && <Knowledge search={search} setSearch={setSearch} topics={filteredTopics} selected={topic} setSelected={setTopic} />}
        {view === 'profile' && <Profile email={userEmail} />}
      </div>
    </main>
  </div>
}

function Landing({ onStart, onExplore }: { onStart: () => void; onExplore: () => void }) { return <main className="landing"><div className="landing-nav"><div className="brand"><span className="brand-mark"><Shield size={19} /></span><span>Cyber<span>Shield</span></span></div><div className="landing-links"><button onClick={onExplore}>Knowledge Base</button><button onClick={onStart}>Sign in</button></div></div><section className="hero"><div className="eyebrow"><span className="pulse" /> Personal security, simplified</div><h1>Your digital safety,<br /><em>made visible.</em></h1><p>CyberShield turns everyday security habits into a clear, actionable plan. Know where you stand. Know what to do next.</p><div className="hero-actions"><button className="button primary" onClick={onStart}>Check your security <ArrowRight size={16} /></button><button className="button ghost" onClick={onExplore}>Explore the knowledge base</button></div><div className="trust-row"><span><LockKeyhole size={14} /> Private by design</span><span><Check size={14} /> 8-minute assessment</span><span><Sparkles size={14} /> Practical recommendations</span></div></section><section className="landing-preview"><div className="preview-label">A clearer view of your digital life</div><div className="preview-card"><div className="preview-top"><span className="dot green" /> Current security posture <span className="status">Good standing</span></div><div className="preview-body"><div className="score-ring"><strong>78</strong><span>/100</span></div><div><h3>Your security is on the right track.</h3><p>A few focused improvements could make a meaningful difference.</p><button onClick={onStart}>View your action plan <ArrowRight size={14} /></button></div></div><div className="preview-bars"><span>Passwords <i style={{ width: '82%' }} /></span><span>Phishing awareness <i style={{ width: '68%' }} /></span><span>Device security <i style={{ width: '91%' }} /></span></div></div></section></main> }

function Auth({ mode, setMode, email, setEmail, password, setPassword, message, onSubmit, onBack }: { mode: 'login' | 'signup'; setMode: (mode: 'login' | 'signup') => void; email: string; setEmail: (email: string) => void; password: string; setPassword: (password: string) => void; message: string; onSubmit: (event: React.FormEvent) => void; onBack: () => void }) { return <main className="auth-page"><div className="auth-panel"><button className="back-link" onClick={onBack}><ChevronLeft size={15} /> Back to home</button><div className="brand auth-brand"><span className="brand-mark"><Shield size={19} /></span><span>Cyber<span>Shield</span></span></div><div className="auth-copy"><div className="eyebrow">Secure workspace</div><h1>{mode === 'login' ? 'Welcome back.' : 'Take control.'}</h1><p>{mode === 'login' ? 'Continue your security journey.' : 'Create your personal security workspace.'}</p></div><form onSubmit={onSubmit} className="auth-form"><label>Email address<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required autoComplete="email" /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required minLength={8} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} /></label><button className="button primary full">{mode === 'login' ? 'Sign in' : 'Create account'} <ArrowRight size={16} /></button>{message && <div className="notice">{message}</div>}</form><div className="auth-switch">{mode === 'login' ? 'New to CyberShield?' : 'Already have an account?'} <button onClick={() => setMode(mode === 'login' ? 'signup' : 'login')}>{mode === 'login' ? 'Create an account' : 'Sign in'}</button></div><small className="auth-note"><LockKeyhole size={13} /> Supabase-secured authentication</small></div><div className="auth-aside"><div className="grid-glow" /><div><span className="aside-number">01</span><h2>Security is not a destination.<br /><em>It is a practice.</em></h2><p>Get the clarity and confidence to make safer choices online.</p></div></div></main> }

function Dashboard({ risk, score, onStart, onKnowledge, onHistory }: { risk: string; score: number; onStart: () => void; onKnowledge: () => void; onHistory: () => void }) { return <div><div className="page-heading"><div><div className="eyebrow">Tuesday, September 10, 2026</div><h1>Good morning, Alex.</h1><p>Here is your personal security overview.</p></div><button className="button primary" onClick={onStart}><Gauge size={16} /> Start assessment</button></div><div className="dashboard-grid"><section className="card posture-card"><div className="card-head"><div><span className="label">Current security posture</span><h2>{risk === 'Low' ? 'Looking good.' : 'Room to improve.'}</h2></div><span className={`risk-badge ${risk.toLowerCase()}`}><span /> {risk} risk</span></div><div className="posture-content"><div className="score-ring large"><strong>{score}</strong><span>/100</span></div><div className="posture-copy"><p>Your score is based on your latest completed assessment. Keep building small, consistent habits.</p><button className="text-link" onClick={onHistory}>View assessment history <ArrowRight size={14} /></button></div></div><div className="metric-row"><div><span>Last assessment</span><strong>Sep 04, 2026</strong></div><div><span>Next check-in</span><strong>In 24 days</strong></div><div><span>Strongest area</span><strong>Device security</strong></div></div></section><section className="card action-card"><div className="card-head"><div><span className="label">Your next best action</span><h3>Strengthen your passwords</h3></div><span className="action-icon"><LockKeyhole size={19} /></span></div><p>Unique passwords are the foundation of your digital security. A password manager makes this effortless.</p><button className="button outline" onClick={onKnowledge}>Learn how <ArrowRight size={15} /></button></section></div><div className="section-heading"><div><span className="label">Keep learning</span><h2>Build better habits</h2></div><button className="text-link" onClick={onKnowledge}>View all topics <ArrowRight size={14} /></button></div><div className="topic-grid">{topics.slice(0, 3).map((item) => <button className="topic-card" key={item.title} onClick={onKnowledge}><item.icon size={18} /><span>{item.title}</span><p>{item.desc}</p><ArrowRight size={15} /></button>)}</div></div> }

function Assessment({ step, selected, answerCount, onSelect, onNext, onBack }: { step: number; selected: number | null; answerCount: number; onSelect: (points: number) => void; onNext: () => void; onBack: () => void }) { const question = questions[step]; return <div className="assessment"><div className="assessment-top"><button className="back-link" onClick={onBack}><ChevronLeft size={15} /> Back</button><span>Assessment <strong>{step + 1} / {questions.length}</strong></span></div><div className="progress"><i style={{ width: `${((step + 1) / questions.length) * 100}%` }} /></div><div className="question-wrap"><div className="question-meta"><span className="eyebrow">{question.category}</span><span>{Math.round((step / questions.length) * 8)} min left</span></div><h1>{question.prompt}</h1><p>Choose the answer that best reflects your everyday habits.</p><div className="answer-list">{question.options.map((option) => <button className={`answer ${selected === option.points ? 'selected' : ''}`} key={option.label} onClick={() => onSelect(option.points)}><span className="answer-radio">{selected === option.points && <Check size={14} />}</span><span>{option.label}</span><span className="answer-arrow"><ChevronRight size={16} /></span></button>)}</div><div className="question-actions"><span>{answerCount} of {questions.length} answered</span><button className="button primary" disabled={selected === null} onClick={onNext}>{step === questions.length - 1 ? 'See my results' : 'Continue'} <ArrowRight size={16} /></button></div></div></div> }

function Results({ score, risk, answers, onRetake, onDashboard }: { score: number; risk: string; answers: number[]; onRetake: () => void; onDashboard: () => void }) { const categoryScores = questions.map((q, i) => ({ category: q.category, score: Math.round(100 - ((answers[i] ?? 2) / 4) * 100) })); return <div><div className="page-heading"><div><div className="eyebrow">Assessment complete</div><h1>Your security snapshot.</h1><p>A practical read on your current digital habits.</p></div><button className="button outline" onClick={onRetake}>Retake assessment</button></div><div className="results-hero card"><div className="result-main"><div className="score-ring huge"><strong>{score}</strong><span>/100</span></div><div><span className={`risk-badge ${risk.toLowerCase()}`}><span /> {risk} risk</span><h2>{risk === 'Low' ? 'You are building strong habits.' : 'You have a clear path forward.'}</h2><p>Your answers show meaningful awareness. Focus on the recommendations below to keep reducing risk.</p></div></div><div className="result-actions"><button className="button primary" onClick={onDashboard}>Return to dashboard <ArrowRight size={15} /></button></div></div><div className="results-grid"><section className="card"><div className="card-head"><div><span className="label">Category breakdown</span><h3>Where you stand</h3></div></div><div className="category-list">{categoryScores.map((item) => <div className="category-row" key={item.category}><span>{item.category}</span><div className="bar"><i style={{ width: `${item.score}%` }} /></div><strong>{item.score}</strong></div>)}</div></section><section className="card recommendations"><span className="label">Recommended next steps</span><h3>Small changes, meaningful impact.</h3><div className="recommendation"><Check size={16} /><div><strong>Use a password manager</strong><p>Create and store unique passwords automatically.</p></div></div><div className="recommendation"><Check size={16} /><div><strong>Turn on multi-factor authentication</strong><p>Add another layer to your most important accounts.</p></div></div><div className="recommendation"><Check size={16} /><div><strong>Practice the pause</strong><p>Verify urgent messages before taking action.</p></div></div></section></div></div> }

function History({ onStart }: { onStart: () => void }) { return <div><div className="page-heading"><div><div className="eyebrow">Your progress</div><h1>Assessment history.</h1><p>Track how your habits improve over time.</p></div><button className="button primary" onClick={onStart}>New assessment <ArrowRight size={16} /></button></div><section className="card history-card"><div className="history-head"><div><span className="label">Score trend</span><h2>Moving in the right direction.</h2></div><span className="trend">+12 pts <small>since first check</small></span></div><div className="chart"><div className="chart-line" /><span className="chart-point p1">58</span><span className="chart-point p2">66</span><span className="chart-point p3">78</span><div className="chart-labels"><span>Jun 12</span><span>Jul 18</span><span>Sep 04</span></div></div></section><section className="card table-card"><div className="card-head"><div><span className="label">Completed assessments</span><h3>Your check-ins</h3></div></div><div className="history-item"><span className="history-date">04 <small>SEP<br />2026</small></span><div><strong>Personal security assessment</strong><p>8 questions · Completed</p></div><strong className="history-score">78 <small>/100</small></strong><span className="risk-badge low"><span /> Low risk</span></div><div className="history-item"><span className="history-date">18 <small>JUL<br />2026</small></span><div><strong>Personal security assessment</strong><p>8 questions · Completed</p></div><strong className="history-score">66 <small>/100</small></strong><span className="risk-badge medium"><span /> Medium risk</span></div></section></div> }

function Knowledge({ search, setSearch, topics: filtered, selected, setSelected }: { search: string; setSearch: (value: string) => void; topics: typeof topics; selected: typeof topics[number]; setSelected: (topic: typeof topics[number]) => void }) { return <div><div className="page-heading"><div><div className="eyebrow">Learn with confidence</div><h1>Knowledge base.</h1><p>Clear answers for a safer digital life.</p></div><div className="search-wrap"><Search size={16} /><input placeholder="Search topics" value={search} onChange={(e) => setSearch(e.target.value)} /></div></div><div className="knowledge-layout"><section className="topic-directory">{filtered.map((item) => <button className={`directory-item ${selected.title === item.title ? 'chosen' : ''}`} key={item.title} onClick={() => setSelected(item)}><item.icon size={18} /><span><strong>{item.title}</strong><small>{item.desc}</small></span><ChevronRight size={16} /></button>)}</section><section className="card detail-card"><div className="detail-icon"><selected.icon size={24} /></div><span className="eyebrow">Understanding {selected.title.toLowerCase()}</span><h2>{selected.title}</h2><p>{selected.desc}</p><div className="detail-columns"><div><span className="label">Warning signs</span>{selected.signs.map((sign) => <div className="detail-line" key={sign}><Flag size={14} /> {sign}</div>)}</div><div><span className="label">Prevention tips</span>{selected.tips.map((tip) => <div className="detail-line" key={tip}><Check size={14} /> {tip}</div>)}</div></div><div className="detail-callout"><Sparkles size={17} /><span><strong>Remember:</strong> The safest response is usually to slow down, verify, and ask for help when something feels off.</span></div></section></div></div> }

function Profile({ email }: { email: string }) { return <div><div className="page-heading"><div><div className="eyebrow">Workspace settings</div><h1>Profile & settings.</h1><p>Manage your account and security preferences.</p></div></div><div className="profile-grid"><section className="card profile-card"><div className="profile-avatar">AS</div><h2>Alex Morgan</h2><p>{email}</p><button className="button outline">Edit profile</button></section><section className="card settings-card"><span className="label">Security preferences</span><div className="setting-row"><div><strong>Assessment reminders</strong><p>Monthly check-in notifications</p></div><span className="toggle on"><i /></span></div><div className="setting-row"><div><strong>Security alerts</strong><p>Important updates and new threats</p></div><span className="toggle on"><i /></span></div><div className="setting-row"><div><strong>Data privacy</strong><p>Your assessment data is only visible to you</p></div><LockKeyhole size={16} /></div></section></div></div> }
